name: Test Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: |
          docker-compose up -d
      - name: Run Tests
        run: |
          docker-compose run web python manage.py collectstatic
          docker-compose run web python manage.py test
